### ISSUE TITLE
您好，想求一份so的源码学习一下，仅用于学习

### ISSUE THREAD

**Issue by YuGongCharley** [GthanosAI/FaceDetectAndRecogize#7]
最近在自学这方面知识，之前也没有怎么接触过底层的代码，所以看到合适的想求一份so库的源码学习一下，不会用在其他用途，只是自己学习用，如果方便的话可以QQ联系，万分感谢。QQ：790447014

**Comment by GthanosAI** [comment]
最近一段时间有点忙，一直没有维护，一个月后，我会把所有的代码都丢出来包括jni部分

**Comment by YuGongCharley** [comment]
@GthanosAI 哇！十分感谢！您这个demo感觉是最靠谱的一个了，我找了好多demo都感觉没您这个好。老师最近让我学人脸这方面，如果您最近这两天有时间可以私发一份吗？QQ邮箱就行，谢谢！！

**Comment by YuGongCharley** [comment]
@GthanosAI 请问您这个人脸识别的模型是用的mobilefacenet吗？还有您是用哪个框架做的训练？谢谢

**Comment by GthanosAI** [comment]
@YuGongCharley insightface + mtcnn

**Comment by YuGongCharley** [comment]
@好的谢谢

**Comment by YuGongCharley** [comment]
@GthanosAI 您好，想请教一下，我自己用cpp写demo的时候将人脸特征值保存为bin文件，但是读取的时候全都乱掉了，想请教您在这部分操作时用的是什么办法？下面这个图上面的一堆0的是乱掉的，下面的是正常的，谢谢！🙏
![屏幕快照 2019-05-16 下午7 59 33](https://user-images.githubusercontent.com/23618226/57852894-f1a13b80-7816-11e9-92f3-263331b36191.png)

**Comment by GthanosAI** [comment]
没有特别的方法，直接文件读取二进制文件，然后直接memcpy.

**Comment by YuGongCharley** [comment]
@GthanosAI 
我仔细走了一下我的代码，可能是从写文件的时候就出错了，我是用文件流写的，文件流要求的格式是char* ，可是人脸特征的格式是vector<float>，想请教一下应该怎样讲vector<float>写入文件？谢谢

**Comment by YuGongCharley** [comment]
我也完成自己的demo了，谢谢您的帮助

**Comment by h3clikejava** [comment]
> 我也完成自己的demo了，谢谢您的帮助

同学考虑开源吗？我跟你遇到一样的情况了，搭把手帮一下

**Comment by YuGongCharley** [comment]
> > 我也完成自己的demo了，谢谢您的帮助
> 
> 同学考虑开源吗？我跟你遇到一样的情况了，搭把手帮一下

开源了的，你应该还在我的项目里发过issue，是一个so库的问题，我的so是在公司电脑编译的，但是安卓项目是在我自己的电脑上开发的，所以应该不会有路径问题
